version: "3.7"

services:
  database_financial:
    image: bitnami/postgresql
    container_name: database_financial
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apisolid
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: financial
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_financial
    depends_on:
      - database_financial

volumes:
  pgdata:
    driver: local